# Copyright (c) 2022 ActiveChooN
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v -vet=off ./...

  Check:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run go staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        install-go: false

    - name: Run go lint
      uses: golangci/golangci-lint-action@v3

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v -vet=off ./...