# Copyright (c) 2022 ActiveChooN
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

  Lint:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run go lint
      uses: golangci/golangci-lint-action@v6

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v -vet=off ./...